#! /bin/bash
cd ~gitolite
chown gitolite: .

UMASK=$(umask)
umask go-rx
mkdir -p .ssh_host

HOST_KEYS=''
for ALG in rsa dsa ecdsa ed25519
do
[ -e .ssh_host/ssh_host_${ALG}_key ] || ssh-keygen -N '' -t ${ALG} -f .ssh_host/ssh_host_${ALG}_key
HOST_KEYS="${HOST_KEYS} -h .ssh_host/ssh_host_${ALG}_key"
done

umask $UMASK

[ -e projects.list ] || sudo -u gitolite -H bash -c "gitolite setup -pk \"$PK_PATH\""

exec /usr/bin/sshd -eD -p 2222 -o PasswordAuthentication=no -o PidFile=none $HOST_KEYS
